services:

  postgres:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clau
      - POSTGRES_PASSWORD=?Server1?
      - POSTGRES_DB=postgresql_database

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=clau
      - MYSQL_PASSWORD=?Server1?
      - MYSQL_ROOT_PASSWORD=?Server1?
      - MYSQL_DATABASE=homeProject